---

- name: "conf: Create /usr/local/etc/pkg"
  file:
    state: "directory"
    path: "/usr/local/etc/pkg"
    owner: "{{ pkg_owner }}"
    group: "{{ pkg_group }}"
    mode: "0755"

- name: "conf: Create /usr/local/etc/pkg/repos"
  file:
    state: "directory"
    path: "/usr/local/etc/pkg/repos"
    owner: "{{ pkg_owner }}"
    group: "{{ pkg_group }}"
    mode: "0755"

- name: "conf: Configure /usr/local/etc/pkg/repos/FreeBSD.conf"
  template:
    src: "FreeBSD.conf.j2"
    dest: "/usr/local/etc/pkg/repos/FreeBSD.conf"
    owner: "{{ pkg_owner }}"
    group: "{{ pkg_group }}"
    mode: "0644"
    backup: no

- name: "conf: Configure package repositories"
  template:
    src: "repo.j2"
    dest: "/usr/local/etc/pkg/repos/{{ item.name }}.conf"
    owner: "{{ pkg_owner }}"
    group: "{{ pkg_group }}"
    mode: "0644"
    backup: no
  with_items: "{{ pkg_repo }}"

# EOF
...
