---
# tasks for freebsd_packages

- import_tasks: vars.yml
  tags: [pkg_vars, always]

- import_tasks: debug.yml
  when: pkg_debug
  tags: [pkg_debug, always]

- import_tasks: conf.yml
  tags: pkg_conf

- import_tasks: packages.yml
  when: freebsd_install_method|lower == "packages"
  tags: pkg_packages

# EOF
...
