---
# tasks for freebsd-packages

- import_tasks: debug.yml
  when: pkg_debug
  tags: pkg_debug

- import_tasks: conf.yml
  tags: pkg_conf

- import_tasks: packages.yml
  when: not pkg_dryrun
  tags: pkg_packages

# EOF
...
