---
# TODO: Implement pkgng annotation.

# - name: "packages: Debug"
#   debug:
#     msg: "{{ item.1 }}"
#   loop: "{{ pkg_dict | subelements('packages') }}"
#   when: pkg_debug

- name: "packages: Install packages individualy from lists in the dictionary"
  pkgng:
    name: "{{ item.1 }}"
    autoremove: "{{ pkg_autoremove | default(omit) }}"
    cached: "{{ pkg_cached | default(omit) }}"
    chroot: "{{ pkg_chroot | default(omit) }}"
    jail: "{{ pkg_jail | default(omit) }}"
    pkgsite: "{{ pkg_pkgsite | default(omit) }}"
    rootdir: "{{ pkg_rootdir | default(omit) }}"
  with_subelements:
    - "{{ pkg_dict }}"
    - packages
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: pkg_install_individually

- name: "packages: Install lists of packages from the dictionary"
  pkgng:
    name: "{{ item.1 }}"
    autoremove: "{{ pkg_autoremove | default(omit) }}"
    cached: "{{ pkg_cached | default(omit) }}"
    chroot: "{{ pkg_chroot | default(omit) }}"
    jail: "{{ pkg_jail | default(omit) }}"
    pkgsite: "{{ pkg_pkgsite | default(omit) }}"
    rootdir: "{{ pkg_rootdir | default(omit) }}"
  loop: "{{ lookup('subelements', pkg_dict, 'packages') }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: not pkg_install_individually

- name: "packages: Install packages individualy from the list"
  pkgng:
    name: "{{ item }}"
    autoremove: "{{ pkg_autoremove }}"
    cached: "{{ pkg_cached }}"
    chroot: "{{ pkg_chroot | default(omit) }}"
    jail: "{{ pkg_jail | default(omit) }}"
    pkgsite: "{{ pkg_site | default(omit) }}"
    rootdir: "{{ pkg_rootdir | default(omit) }}"
  loop: "{{ pkg_list }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: pkg_install_individually

- name: "packages: Install list of packages"
  pkgng:
    name: "{{ pkg_list }}"
    autoremove: "{{ pkg_autoremove }}"
    cached: "{{ pkg_cached }}"
    chroot: "{{ pkg_chroot | default(omit) }}"
    jail: "{{ pkg_jail | default(omit) }}"
    pkgsite: "{{ pkg_site | default(omit) }}"
    rootdir: "{{ pkg_rootdir | default(omit) }}"
  when: not pkg_install_individually
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"

- name: "packages: Deinstall packages individually from the list"
  pkgng:
    state: "absent"
    name: "{{ item }}"
    autoremove: "{{ pkg_autoremove }}"
    cached: "{{ pkg_cached }}"
    chroot: "{{ pkg_chroot | default(omit) }}"
    jail: "{{ pkg_jail | default(omit) }}"
    pkgsite: "{{ pkg_site | default(omit) }}"
    rootdir: "{{ pkg_rootdir | default(omit) }}"
  loop: "{{ pkg_list_deinstall }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: pkg_install_individually

- name: "packages: Deinstall list of packages"
  pkgng:
    state: "absent"
    name: "{{ pkg_list_deinstall }}"
    autoremove: "{{ pkg_autoremove }}"
    cached: "{{ pkg_cached }}"
    chroot: "{{ pkg_chroot | default(omit) }}"
    jail: "{{ pkg_jail | default(omit) }}"
    pkgsite: "{{ pkg_site | default(omit) }}"
    rootdir: "{{ pkg_rootdir | default(omit) }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when: not pkg_install_individually

# EOF
...
